# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Key words
    url: tags/
    weight: 20
  - name: About
    url: uses/
    weight: 30
  - name: Daily
    url: daily/
    weight: 30
