# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Key words
    url: tags/
    weight: 20
  - name: daily
    url: uses/
    weight: 30
